const ASTRO_DATA = {
  ZODIAC_SIGNS: [
    "Aries",
    "Taurus",
    "Gemini",
    "Cancer",
    "Leo",
    "Virgo",
    "Libra",
    "Scorpio",
    "Sagittarius",
    "Capricorn",
    "Aquarius",
    "Pisces",
  ],

  TAMIL_ZODIAC: [
    "மேஷம்",
    "ரிஷபம்",
    "மிதுனம்",
    "கடகம்",
    "சிம்மம்",
    "கன்னி",
    "துலாம்",
    "விருச்சிகம்",
    "தனுசு",
    "மகரம்",
    "கும்பம்",
    "மீனம்",
  ],

  PLANETS: ["Sun", "Moon", "Mars", "Mercury", "Jupiter", "Venus", "Saturn", "Rahu", "Ketu"],

  // Added months array here
  MONTHS: [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
  ],

  // API Configuration - moved here for centralized management
  API_CONFIG: {
    keys: [
      "byjkLONPLI4qFC2yo8M932zrz6JXtdDM5bGB9Eyf",
      "7nIdDyNmyW9NcHOOXv9Ez6rtl1CeA1NjaQNxD4tV",
      "MXy7NJiYCT5DNygveWQL15JP1DxYCr4u4mCkFtVq",
      "sZUSVdEFVc7m9A543JdE78IYw1XzX5Vs7ZH7cHtl",
    ],
    endpoints: {
      astroBase: "https://json.apiastro.com",
      timezone: "https://api.timezonedb.com/v2.1/get-time-zone?key=H2P5C3OCWUR0",
      nominatim: "https://nominatim.openstreetmap.org/search",
    },
  },

  // Form field configurations
  FORM_FIELDS: [
    { id: "date", label: "Date", range: [1, 31] },
    { id: "month", label: "Month", type: "select", options: "months" },
    { id: "year", label: "Year", range: [-100, 100] },
    { id: "hours", label: "Hours", range: [1, 12] },
    { id: "minutes", label: "Minutes", range: [0, 59] },
    { id: "seconds", label: "Seconds", range: [0, 59] },
    { id: "ampm", label: "AM/PM", options: ["AM", "PM"] },
  ],

  HOUSE_DESCRIPTIONS: {
    1: "Self - Physical body, personality, appearance, and self-expression.",
    2: "Wealth - Money, possessions, values, and material resources.",
    3: "Communication - siblings, Mental integrity, courage, friends, donations, communication, and short travels.",
    4: "Home - skills, home environment, vehicles, roots, and mother hood.",
    5: "Creativity - Children, creative expression, love, and entertainment.",
    6: "Health - Health, daily routines, jail, service to others, and work environment.",
    7: "Relationships - Partnerships, marriage, business relationships, and open enemies.",
    8: "Transformation - Transformation, diseases, death, bad friendships, enemity, and sexuality.",
    9: "Philosophy - Higher education, philosophy, religion, long-distance travel, and law.",
    10: "Career - Career, public image, reputation, and authority.",
    11: "Friends - Friendships, social groups, aspirations, and humanitarian pursuits, land, Indication of good spouse",
    12: "Spirituality - Abroad, Sexlife, Arguements, Multiple business, Occult Science, Secrets",
  },

  NAKSHATRA_MAPPING: {
    Aswini: "அஸ்வினி",
    Bharani: "பரணி",
    Krittika: "கிருத்திகை",
    Rohini: "ரோகிணி",
    Mrigasira: "மிருகசீரிடம்",
    Aardra: "திருவாதிரை",
    Punarvasu: "புனர்பூசம்",
    Pushyami: "பூசம்",
    Aaslesha: "ஆயில்யம்",
    Makha: "மகம்",
    "Poorva Phalguni(Pubba)": "பூரம்",
    "Uttara Phalguni(Uttara)": "உத்திரம்",
    Hasta: "அஸ்தம்",
    Chitta: "சித்திரை",
    Swati: "சுவாதி",
    Visakha: "விசாகம்",
    Anuradha: "அனுஷம்",
    Jyeshta: "கேட்டை",
    Moola: "மூலம்",
    Poorvaashaada: "பூராடம்",
    Uttaraashaada: "உத்திராடம்",
    Sravanam: "திருவோணம்",
    Dhanishta: "அவிட்டம்",
    Satabisha: "சதயம்",
    Poorvaabhadra: "பூரட்டாதி",
    Uttaraabhadra: "உத்திரட்டாதி",
    Revati: "ரேவதி",
  },

  ZODIAC_STATUS: {
    Aries: {
      Sun: "Exalted",
      Moon: "Neutral",
      Mars: "Mooltrikona",
      Mercury: "Neutral",
      Jupiter: "Friendly",
      Venus: "Neutral",
      Saturn: "Debilitated",
      Rahu: "Enemy",
      Ketu: "Enemy",
    },
    Taurus: {
      Sun: "Enemy",
      Moon: "Exalted",
      Mars: "Neutral",
      Mercury: "Friendly",
      Jupiter: "Enemy",
      Venus: "Mooltrikona",
      Saturn: "Friendly",
      Rahu: "Debilitated",
      Ketu: "Debilitated",
    },
    Gemini: {
      Sun: "Neutral",
      Moon: "Friendly",
      Mars: "Enemy",
      Mercury: "Mooltrikona",
      Jupiter: "Enemy",
      Venus: "Friendly",
      Saturn: "Friendly",
      Rahu: "Friendly",
      Ketu: "Friendly",
    },
    Cancer: {
      Sun: "Neutral",
      Moon: "Mooltrikona",
      Mars: "Debilitated",
      Mercury: "Enemy",
      Jupiter: "Exalted",
      Venus: "Enemy",
      Saturn: "Enemy",
      Rahu: "Enemy",
      Ketu: "Enemy",
    },
    Leo: {
      Sun: "Mooltrikona",
      Moon: "Friendly",
      Mars: "Friendly",
      Mercury: "Friendly",
      Jupiter: "Friendly",
      Venus: "Enemy",
      Saturn: "Enemy",
      Rahu: "Enemy",
      Ketu: "Enemy",
    },
    Virgo: {
      Sun: "Neutral",
      Moon: "Friendly",
      Mars: "Enemy",
      Mercury: "Mooltrikona_Exalted",
      Jupiter: "Friendly",
      Venus: "Debilitated",
      Saturn: "Friendly",
      Rahu: "Friendly",
      Ketu: "Friendly",
    },
    Libra: {
      Sun: "Debilitated",
      Moon: "Neutral",
      Mars: "Neutral",
      Mercury: "Friendly",
      Jupiter: "Enemy",
      Venus: "Mooltrikona",
      Saturn: "Exalted",
      Rahu: "Friendly",
      Ketu: "Friendly",
    },
    Scorpio: {
      Sun: "Friendly",
      Moon: "Neutral",
      Mars: "Mooltrikona",
      Mercury: "Neutral",
      Jupiter: "Friendly",
      Venus: "Neutral",
      Saturn: "Enemy",
      Rahu: "Exalted",
      Ketu: "Exalted",
    },
    Sagittarius: {
      Sun: "Friendly",
      Moon: "Neutral",
      Mars: "Friendly",
      Mercury: "Neutral",
      Jupiter: "Mooltrikona",
      Venus: "Friendly",
      Saturn: "Neutral",
      Rahu: "Friendly",
      Ketu: "Friendly",
    },
    Capricorn: {
      Sun: "Enemy",
      Moon: "Neutral",
      Mars: "Exalted",
      Mercury: "Neutral",
      Jupiter: "Debilitated",
      Venus: "Friendly",
      Saturn: "Mooltrikona",
      Rahu: "Friendly",
      Ketu: "Friendly",
    },
    Aquarius: {
      Sun: "Enemy",
      Moon: "Neutral",
      Mars: "Neutral",
      Mercury: "Neutral",
      Jupiter: "Neutral",
      Venus: "Friendly",
      Saturn: "Mooltrikona",
      Rahu: "Enemy",
      Ketu: "Enemy",
    },
    Pisces: {
      Sun: "Friendly",
      Moon: "Neutral",
      Mars: "Friendly",
      Mercury: "Debilitated",
      Jupiter: "Mooltrikona",
      Venus: "Exalted",
      Saturn: "Neutral",
      Rahu: "Friendly",
      Ketu: "Friendly",
    },
  },

  COMBUSTION_RULES: {
    Sun: { isSource: true },
    Mercury: { distance: 14 },
    Venus: { distance: 10 },
    Mars: { distance: 17 },
    Jupiter: { distance: 11 },
    Saturn: { distance: 15 },
  },

  ASPECTS: {
    Sun: [7],
    Moon: [7],
    Mars: [4, 7, 8],
    Mercury: [7],
    Jupiter: [5, 7, 9],
    Venus: [7],
    Saturn: [3, 7, 10],
    Rahu: [5, 7, 9],
    Ketu: [5, 7, 9],
  },

  HOUSE_LORDS: {
    Aries: "Mars",
    Taurus: "Venus",
    Gemini: "Mercury",
    Cancer: "Moon",
    Leo: "Sun",
    Virgo: "Mercury",
    Libra: "Venus",
    Scorpio: "Mars",
    Sagittarius: "Jupiter",
    Capricorn: "Saturn",
    Aquarius: "Saturn",
    Pisces: "Jupiter",
  },
};

// Make it available globally
if (typeof window !== "undefined") {
  window.ASTRO_DATA = ASTRO_DATA;
}

export { ASTRO_DATA };